# Generated by Django 5.0.4 on 2024-04-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0004_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='updated_date',
            field=models.DateField(auto_now=True),
        ),
    ]
